<a href="https://colab.research.google.com/github/artur-trotskyi/api/blob/master/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [ ]:
v = np.arange(1, 11, 1, dtype=int)
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
a = np.zeros((3, 3), dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
a = np.random.randint(1, 11, size=(5, 5))
a

array([[ 7,  7,  3,  9,  3],
       [ 7, 10,  9,  1,  5],
       [ 8,  2, 10,  9, 10],
       [ 2,  9,  8, 10, 10],
       [ 2,  7,  3,  8,  7]])

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
a = np.random.random(size=(4, 4))
a

array([[0.7673163 , 0.5442026 , 0.66304923, 0.88998063],
       [0.78698448, 0.564963  , 0.93645571, 0.42200473],
       [0.82477617, 0.09188121, 0.34386313, 0.19042324],
       [0.24016673, 0.6636372 , 0.23655549, 0.37971787]])

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
a = np.random.randint(1, 10, size=5)
a

array([3, 2, 8, 9, 4])

In [ ]:
b = np.random.randint(1, 10, size=5)
b

array([9, 2, 2, 4, 2])

In [ ]:
a + b

array([12,  4, 10, 13,  6])

In [ ]:
a - b

array([-6,  0,  6,  5,  2])

In [ ]:
a * b

array([27,  4, 16, 36,  8])

6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
a = np.random.randint(1, 10, size=7)
b = np.random.randint(1, 10, size=7)
np.dot(a, b)

132

7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
a = np.random.randint(1, 10, size=(2, 2))
b = np.random.randint(1, 10, size=(2, 3))
np.dot(a, b)

array([[69, 60, 62],
       [68, 40, 64]])

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
a = np.random.randint(1, 10, size=(3, 3))
a

array([[4, 2, 3],
       [2, 9, 3],
       [3, 3, 3]])

In [ ]:
np.linalg.inv(a)

array([[ 1.2       ,  0.2       , -1.4       ],
       [ 0.2       ,  0.2       , -0.4       ],
       [-1.4       , -0.4       ,  2.13333333]])

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
a = np.random.random(size=(4, 4))
a

array([[0.36305999, 0.24848749, 0.8133304 , 0.95338249],
       [0.1766976 , 0.9504348 , 0.93758525, 0.29333532],
       [0.07618944, 0.24825568, 0.46777286, 0.73116263],
       [0.71562394, 0.0581386 , 0.68292371, 0.01823634]])

In [ ]:
a.T

array([[0.36305999, 0.1766976 , 0.07618944, 0.71562394],
       [0.24848749, 0.9504348 , 0.24825568, 0.0581386 ],
       [0.8133304 , 0.93758525, 0.46777286, 0.68292371],
       [0.95338249, 0.29333532, 0.73116263, 0.01823634]])

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [ ]:
a = np.random.randint(1, 10, size=(3, 4))
a

array([[6, 1, 7, 8],
       [3, 8, 7, 8],
       [0, 6, 1, 7]])

In [ ]:
v = np.random.randint(1, 11, size=4)
v

array([5, 8, 3, 3])

In [ ]:
a * v

array([[30,  8, 21, 24],
       [15, 64, 21, 24],
       [ 0, 48,  3, 21]])

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [ ]:
a = np.random.random(size=(2, 3))
a

array([[0.04609521, 0.1934861 , 0.78056459],
       [0.85688451, 0.44413263, 0.14185524]])

In [ ]:
v = np.random.random(size=3)
v

array([0.58197695, 0.68852792, 0.50594612])

In [ ]:
a * v

array([[0.02682635, 0.13322058, 0.39492362],
       [0.49868703, 0.30579771, 0.07177111]])

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
a_1 = np.random.randint(1, 10, size=(2, 2))
a_1

array([[7, 3],
       [9, 3]])

In [ ]:
a_2 = np.random.randint(1, 10, size=(2, 2))
a_2

array([[4, 6],
       [9, 4]])

In [ ]:
a_1 * a_2

array([[28, 18],
       [81, 12]])

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
np.dot(a_1, a_2)

array([[55, 54],
       [63, 66]])

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [ ]:
a = np.random.randint(1, 100, size=(5, 5))
a

array([[83, 37, 55, 14, 23],
       [12, 56, 73, 16, 76],
       [59, 86, 66, 16, 72],
       [80, 23, 13, 53, 25],
       [24, 97,  9, 79, 14]])

In [ ]:
a.sum()

1161

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [ ]:
a_1 = np.random.randint(1, 10, size=(4, 4))
a_1

array([[7, 9, 5, 4],
       [1, 7, 8, 3],
       [3, 7, 1, 3],
       [8, 1, 9, 2]])

In [ ]:
a_2 = np.random.randint(1, 10, size=(4, 4))
a_2

array([[4, 5, 3, 6],
       [4, 4, 7, 7],
       [3, 4, 1, 3],
       [6, 6, 9, 9]])

In [ ]:
a_1 - a_2

array([[ 3,  4,  2, -2],
       [-3,  3,  1, -4],
       [ 0,  3,  0,  0],
       [ 2, -5,  0, -7]])

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [ ]:
a = np.random.random(size=(3, 3))
a

array([[0.88170308, 0.11903346, 0.94484981],
       [0.1032404 , 0.3086418 , 0.40419228],
       [0.56480177, 0.987291  , 0.65447959]])

In [ ]:
sum(a.T)

array([1.94558635, 0.81607448, 2.20657237])

In [ ]:
a.sum(axis=1)

array([1.94558635, 0.81607448, 2.20657237])

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [ ]:
a = np.random.randint(1, 20, size=(3, 4))
a

array([[ 9, 18, 18,  3],
       [ 8,  4,  6, 12],
       [ 7, 13, 18,  8]])

In [ ]:
a * a

array([[ 81, 324, 324,   9],
       [ 64,  16,  36, 144],
       [ 49, 169, 324,  64]])

In [ ]:
a ** 2

array([[ 81, 324, 324,   9],
       [ 64,  16,  36, 144],
       [ 49, 169, 324,  64]])

18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [ ]:
v = np.random.randint(1, 50, size=4)
v

array([13, 41, 45, 35])

In [ ]:
v ** 0.5

array([3.60555128, 6.40312424, 6.70820393, 5.91607978])

In [ ]:
np.sqrt(v)

array([3.60555128, 6.40312424, 6.70820393, 5.91607978])

**Завдання 2 (додаткове, за бажанням)**

1. Замініть усі непарні числа в arr на -1 arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
for index, value in enumerate(arr):
    if value % 2:
        arr[value] = -1

arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

2. Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = arr.reshape((5, 2))

arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

3. Створіть два двовимірні масиви а і b, та складіть масиви їх вертикально

> Додати блок цитати



In [12]:
a = np.random.randint(-10, 10, size=(2, 2))
a

array([[0, 7],
       [3, 1]])

In [13]:
b = np.random.randint(-10, 10, size=(2, 2))
b

array([[ -7,   6],
       [  6, -10]])

In [14]:
res = a + b
res

array([[-7, 13],
       [ 9, -9]])

In [15]:
res = np.vstack((a, b))
res

array([[  0,   7],
       [  3,   1],
       [ -7,   6],
       [  6, -10]])

4. Створіть наступний шаблон без жорсткого кодування(Hard coding) . Використовуйте лише функції Numpy і наведений нижче масив введення Input:a = np.array([1,2,3])

Output:array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [17]:
a = np.array([1,2,3])
# Повторення кожного елемента 3 рази
part1 = np.repeat(a, 3)
# Повторення всього масиву 3 рази
part2 = np.tile(a, 3)
output = np.concatenate((part1, part2))
output

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

5. Отримайте спільні елементи між a і b

a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

In [20]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

6. Отримайте позиції перших 5 максимальних значень у заданому масиві a

np.random.seed(100) a = np.random.uniform(1,50, 20)

In [54]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a

array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361])

In [55]:
# Отримуємо індекси відсортованих значень у порядку зростання
sorted_indices = np.argsort(a)
# Беремо останні 5 індексів (найбільші значення) у зворотному порядку
top_5_indices = sorted_indices[-5:][::-1]
top_5_indices

array([15, 10,  3,  7, 18])

In [57]:
top_5 = a[top_5_indices]
top_5

array([48.95256545, 44.67477576, 42.39403048, 41.466785  , 40.99501269])

7. Вилучіть усі значення NaN із одновимірного масиву

а=np.array([1,2,3,np.nan,5,6,7,np.nan])

In [65]:
a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
a_clean = a[~np.isnan(a)]
a_clean

array([1., 2., 3., 5., 6., 7.])

In [70]:
a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
a_clean = np.array([el for el in a if not np.isnan(el)])
a_clean

array([1., 2., 3., 5., 6., 7.])

8. Обчисліть евклідову відстань між двома масивами a і b.

a = np.array([1,2,3,4,5]) b = np.array([4,5,6,7,8])

In [71]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])
distance = np.linalg.norm(a - b)
distance

6.708203932499369

9. Знайдіть індекс 5-го повторення числа 1 у масиві x

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [75]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
rep_count = 0
found_idx = None
for i, val in enumerate(x):
  if val == 1:
    rep_count += 1
    if rep_count == 5:
      found_idx = i

found_idx

8

In [78]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
indices = np.where(x == 1)[0]
fifth_occurrence_index = indices[4]
fifth_occurrence_index

(array([ 0,  2,  3,  7,  8, 10, 11]),)

10. Знайдіть повторювані записи (від 2-го випадку повторення і далі) у заданому масиві і позначте їх як True. Перше повторення має бути False.

Input np.random.seed(100) a = np.random.randint(0, 5, 10)

[0 0 3 0 2 4 2 2 2 2] #Output [False True False True False False True True True True]

In [82]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
a

array([0, 0, 3, 0, 2, 4, 2, 2, 2, 2])

In [83]:
marks = np.zeros_like(a, dtype=bool)
seen = {}
for i, value in enumerate(a):
    if value in seen:
        marks[i] = True
    else:
        seen[value] = 1
marks

array([False,  True, False,  True, False, False,  True,  True,  True,
        True])